### ISSUE TITLE
lots of room for code improvement

### ISSUE THREAD

**Issue by 5rycaa** [stanleyn/VoPo#3]
Hi,

I wanted to leave you a comment if you are interested in getting a feedback of someone who tried to use your tool. I must say that after several days of tinkering around, I am still lost as there are not enough information or description for your code.

But let me share few things so that it help you if you are planning to update some stuff. First of all, I must admit that I haven't used git-lfs at all as it recently reported some security problems. Which means that I basically tried to reverse engineer what your code does by using my own data. 

In the beginning, all is working fine, eg. creating objects like feature frequency, build etc., but as I was mostly interested in the classification, I couldn't get anything out of it except the accuracies of your model. And I would have loved to know which features are the most responsible for separation between the classes. **Have I maybe missed that part somehow?**

The way I understood it, the cool part of your toolset are the visualizations (which is how I should've got my features of interest, I assume), but this is where the **chaos starts**.

1. no legends
2. no titles
3. description is too simplistic and besides explaining what are the inputs, it doesn't really tell you what you get out of it
4. only plots for your mentioned datasets in the paper are those of classification accuracy, while the ones from supplementary datasets (which are the most interesting ones) are completely missing
5. once you look into the code for the paper figures, I finally find commented that there might be the function I would need, but then that function is not as a part of your github (cellViz_foldChange, something like that) and there is a comment to write to the author for more. I think it would be better then to remove that commented section entirely and just leave the message

All in all, I am imagining that your tool might be useful and interesting to use in classification for flow/cyTOF data, as there are not that many new tools published, but unfortunately due to the previously mentioned problems, its less useful than one would hope for.

In case you are planning to do some updates and some cleanup, I think this should serve you as a good starting point.

**Comment by stanleyn** [comment]
thanks for the feedback
